server:
  port: 8001

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/ProfileDB"
    username: "postgres"
    password: "postgres"
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: changelog.xml
    default-schema: "public"
    enabled: true
  flyway:
    enabled: false

kafka:
  stockAdapter:
    group:
      id: "server.broadcast.profile"
    topic: "profile_stock_registered"
  profile:
    topics: "profile_updated,profile_for_stock,profile_completely_created,profile_completely_deleted"
    group:
      id: "server.broadcast.profile"
  server: "localhost:9092"


#
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: prometheus,health
  endpoint:
    prometheus.enabled: true
    health.enabled: true


enable:
  kafka: true
  server:
    kafka: "localhost:9092"
