{
 "title": "PROJECT DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes[5m]) * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[2m]))"
    }
   ]
  },
  {
   "title": "Количество HTTP-запросов для сервиса Профиль",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count { job =~ \"profile-service\"}[5m])"
    }
   ]
  },
  {
   "title": "Количество HTTP-запросов для сервиса Договоры",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count { job =~ \"contract-service\"}[5m])"
    }
   ]
  },
  {
   "title": "Количество сгенерированных событий сервисом Профиль",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(profile_event_produced_total[1m]) "
    }
   ]
  },
  {
   "title": "Количество сгенерированных событий сервисом Договоры",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(contract_produced_total[1m])"
    }
   ]
  },
  {
   "title": "Количество полученных событий от сервиса Договоры",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(contract_event_consumed_total[1m]) "
    }
   ]
  },
  {
   "title": "Количество сгенерированных событий сервисом Адаптер биржи",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stock_adapter_event_produced_total[1m])"
    }
   ]
  },
  {
   "title": "Количество полученных событий от сервиса Адаптер биржи",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stock_adapter_event_consumed_total[1m])"
    }
   ]
  }
 ]
}