apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "contract-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth.default.svc.cluster.local:9000/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Email,X-UserId,X-First-Name,X-Last-Name"
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /contract
            pathType: Prefix
            backend:
              service:
                name: {{ include "contract-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
