apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: contract-service
    context: .
deploy:
  helm:
    releases:
    - name: contract-service
      chartPath: contract-chart
      skipBuildDependencies: true
      values:
        image: contract-service
